### ISSUE TITLE
unite-source-command does not list commands specific to filetype of open buffer

### ISSUE THREAD

**Issue by BonarBeavis** [Shougo/unite.vim#1050]
Here are all possible commands for "Java":

![screenshot from 2015-10-28 19-30-23](https://cloud.githubusercontent.com/assets/3330855/10798930/643a81d0-7daa-11e5-907d-d9bc8b0ca0e5.png)

But unite only lists:

![screenshot from 2015-10-28 19-30-29](https://cloud.githubusercontent.com/assets/3330855/10798940/6e5fb6d0-7daa-11e5-8cb9-4d974013ffff.png)

**Comment by Shougo** [comment]
Fixed.

**Comment by BonarBeavis** [comment]
Thanks a lot, but unfortunately it still does not work. I have the following mapping:

```vim
nnoremap <silent><leader>; :<C-u>Unite -direction=below -buffer-name=command -start-insert command <cr>
```

Do I have to tell Unite explicitly that it should use the current buffer?

**Comment by Shougo** [comment]
@BonarBeavis 
I cannot reproduce the problem.  Please read the issue template.
And you must call unite from Java buffers.

**Comment by BonarBeavis** [comment]
Okay, I reproduced it with vim-fugitive.

* Expected
Command source lists "Gcommit" command

* Environment Information
 * OS: Ubuntu 15.10
 * Vim version:  7.4.712

* Minimal vimrc less than 50 lines

```VimL
" Your vimrc
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'Shougo/unite.vim'
call vundle#end()            " required
" Enable syntax highlighting
syntax on
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
filetype plugin on
"
" Unite
let g:unite_source_history_yank_enable=1
call unite#filters#matcher_default#use(['matcher_fuzzy'])
nnoremap <silent><leader>; :<C-u>Unite -direction=below -buffer-name=command -start-insert command <cr>
"
" Custom mappings for the unite buffer
autocmd FileType unite call s:unite_settings()
function! s:unite_settings()
  " Play nice with supertab
  let b:SuperTabDisabled=1
  " Enable navigation with control-j and control-k in insert mode
  imap <silent><buffer><TAB>   <Plug>(unite_select_previous_line)
  nmap <silent><buffer><expr>s      unite#do_action('vsplit')
  nmap <silent><buffer><expr>i      unite#do_action('split')
eendfunction
```

* How to reproduce

 0. startup vim
 1. open file in git repo
 2. press <leader>; for command source
 3. After hitting "Gc" there is no "Gcommit" selection

* Screen shot (if possible)
Gcommit command ist available in buffer
![screenshot from 2015-10-30 12-50-17](https://cloud.githubusercontent.com/assets/3330855/10845155/ca2cba88-7f05-11e5-835d-fdfd267dc9bd.png)

Gcommit ist missing in command source
![screenshot from 2015-10-30 12-51-12](https://cloud.githubusercontent.com/assets/3330855/10845170/e7c75a8a-7f05-11e5-8d5b-c614287b5205.png)

**Comment by Shougo** [comment]
Thanks.  Reproduced.  Fixed.

**Comment by BonarBeavis** [comment]
Works fine now, thanks a lot!
