### ISSUE TITLE
Don't cache ignored files

### ISSUE THREAD

**Issue by musaffa** [Shougo/unite.vim#1075]
I've this setup for `file_rec/async`:

```vim
call unite#custom#source('file_rec/async', 'ignore_pattern', 'bower_components\|node_modules\|dist\|tmp\|public')
```

Although the unite view doesn't display the ignored files (which is the expected behavior), it creates a cache file which contains all the ignored files as well. My application is typical Ember app which contains ~ 200,000 files. The most of them resides in the node_modules and bower_components directories.

Reading from this large cache file and refreshing it is very slow. Is there any way to ignore the ignored files in the cache?

**Comment by Shougo** [comment]
OK.  I will implement it.

**Comment by musaffa** [comment]
I will be looking forward to it. Please remember to implement this in the other ignore features like `ignore_globs`.

Ctrl-P generates only a few hundreds of lines of cache file. I've manually removed all the unnecessary lines from `Unite`'s cache, `Unite` has become blazing fast. The huge cache file is perhaps one of the core reasons why Unite is a bit sluggish when compared to the other plugins.

**Comment by Shougo** [comment]
Fixed.

**Comment by musaffa** [comment]
@Shougo It is partially fixed.

Now the cache file doesn't contain any ignored files so loading `unite` and searching has become faster. But the cache file is taking the same time to be generated/refreshed as before. What is cache file is doing now is that it is discarding any file which is in the ignored patterns. That's why it is still very slow. To make it faster, the cache file shouldn't be fed with the ignore files at all.

To test this, you can create a default [ember-cli](http://www.ember-cli.com/) app and see what happens.

**Comment by Shougo** [comment]
@musaffa Unfortunately, it is feature.
I don't want to concern about unite performance in more time.
I will rewrite unite.vim for neovim.

**Comment by Shougo** [comment]
> To make it faster, unite shouldn't look into the files of an ignored directory rather discard the directory itself.

You should change the `g:unite_source_rec_async_command`.
Unite just call it.

**Comment by musaffa** [comment]
Ok. I've changed the `file_rec/async`'s command like below:
```vim
let g:unite_source_rec_async_command = ['ag', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', '']
```
As an `ag` feature, it automatically ignores file from `.gitignore` or other vcs ignores. I just had to make sure `.gitignore` lines doesn't have any leading slash. And there's no need to specify `ignore_pattern` in source.

Now it is fast as I expected. Thanks for the tip. :)

**Comment by tex** [comment]
@Shougo will your rewrite of unite support vim too?

**Comment by Shougo** [comment]
> will your rewrite of unite support vim too?

No.  It is the remote plugin for neovim only.
Because, VimL performance is too bad.
