### ISSUE TITLE
file_rec in /mnt returns results when file_rec/neovim does not

### ISSUE THREAD

**Issue by PonderingGrower** [Shougo/unite.vim#1080]
Hi Shougo!

I've encountered a weird bug. I used the following `init.vim`:

```
call plug#begin('~/.config/nvim/bundle')
Plug 'Shougo/unite.vim'
call plug#end()
```
Steps to reproduce:

 1. `mkdir /mnt/thing; touch /mnt/thing/test`
 2. Start vim with the besic `init.vim`.
 3. `:Unite file_rec:/mnt/thing` - Returns `test`.
 4. `:Unite file_rec/neovim:/mnt/thing` - Returns nothing.

I have no idea what this is about.

```
NVIM v0.1.0-39-g3b61598 (compiled Nov 10 2015 23:19:50)
Commit: 3b615980c814eff3fa284dd07b61fbf50885f4ab
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERAT
ED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/build/build/config -I/tmp/build/src -I/tmp/build/.deps/usr/include -I/tmp/build/.deps/usr/include -I/tmp/build/.deps/usr/include/luajit-2.0 -I/tmp/build
/.deps/usr/include -I/tmp/build/.deps/usr/include -I/tmp/build/.deps/usr/include -I/tmp/build/.deps/usr/include -I/usr/include -I/tmp/build/build/src/nvim/auto -I/tmp/build/build/include
Compiled by root@be8abe028e13

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
```

Unite: `1764dc686c29e37d9b10ed4816a99035775b14ff`

**Comment by Shougo** [comment]
Fixed.

**Comment by PonderingGrower** [comment]
Awesome, that fixes the issue for the config I posted, but for some reason it still fails if you add this to the config:
```
call unite#custom#profile('default', 'context', { 'start_insert' : 1 })
```

**Comment by PonderingGrower** [comment]
Actually, it also still doesn't work if you just use the `-start-insert` flag.

**Comment by Shougo** [comment]
@PonderingGrower It is neovim problem.  I cannot fix it.
https://github.com/Shougo/unite.vim/issues/1079

**Comment by PonderingGrower** [comment]
Daaaamn, that's sucky. Wasn't aware of that. Thanks.
