### ISSUE TITLE
Unite window height does not get restored immediately after auto-preview window is closed

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#917]
Problem summary (also the repro):

1. Bring up unite window by "Unite gtags/ref". The height of the unite window is X.
2. Enable auto-preview (\<Plug\>(unite_toggle_auto_preview)). The height of the auto-preview window is Y. The total height of the unite and preview windows together is X+Y.
3. Disable auto-preview. The auto-preview window disappears, but the unite window's height becomes X+Y! That's just ugly, although I can live with it.
4. Then I press 'j' or 'k' and the unite window height goes back to X again. Can it go back to X right after the preview window is closed?

The relevant part of my .vimrc:

```vim
" Unite
call unite#custom#profile('default', 'context', {
\       'direction': 'below',
\       'cursor_line_time': '0.0',
\ })
" Custom mappings for the unite buffer
autocmd FileType unite call s:unite_settings()
function! s:unite_settings()
        nmap <buffer> p <Plug>(unite_toggle_auto_preview)
        " Disable cursor looping
        silent! nunmap <buffer> <Up>
        silent! nunmap <buffer> <Down>
        hi! link CursorLine PmenuSel
endfunction
```

$ cat /etc/issue
CentOS release 6.6 (Final)
Kernel \r on an \m

$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 15 2015 17:37:20)
Huge version without GUI.  Features included (+) or not (-):
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop
+farsi           +mouse_netterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl  -lselinux     -L/usr/lib64/python2.6/config -lpython2.6 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic

**Comment by mrbiggfoot** [comment]
I'll produce the minimal .vimrc a bit later... if it will be still needed.

**Comment by Shougo** [comment]
I will test it.
If I cannot reproduce it, minimal .vimrc is needed.

**Comment by Shougo** [comment]
Reproduced.  It is bug.

**Comment by mrbiggfoot** [comment]
Cool. Thanks for fixing the formatting in my original report, now I know how to format properly :)

**Comment by Shougo** [comment]
Fixed.

**Comment by mrbiggfoot** [comment]
Nope... still broken here. The only difference that I see is that the height of the preview window became greater, otherwise the behavior is unchanged.

**Comment by mrbiggfoot** [comment]
Here's the fix:

``` diff
diff --git a/autoload/unite/mappings.vim b/autoload/unite/mappings.vim
index ccec653..2626b8e 100644
--- a/autoload/unite/mappings.vim
+++ b/autoload/unite/mappings.vim
@@ -752,13 +752,12 @@ function! s:toggle_auto_preview() "{{{
   let unite.preview_candidate = {}

   if context.auto_preview
-    let context.winheight -= &previewheight
     call unite#view#_do_auto_preview()
   elseif !context.auto_preview
         \ && !unite#get_current_unite().has_preview_window
     " Close preview window.
-    let unite.context.winheight += &previewheight
     call unite#view#_close_preview_window()
+       call unite#redraw()
   endif
 endfunction"}}}
 function! s:toggle_auto_highlight() "{{{
```

**Comment by Shougo** [comment]
Fixed again.

> -    let unite.context.winheight += &previewheight

No.  It is needed!

**Comment by mrbiggfoot** [comment]
No, that's a bad fix. It has two problems:
1. Works only if I open auto preview and then close it without navigating in between.
2. Even when it works, it resets the current cursor position in the unite window.
Sorry for the premature post...

**Comment by mrbiggfoot** [comment]
> Fixed again.

Yep, this time it works. Not as I imagine it would (I thought the preview window would appear next to the unite window, not "inside" of it), but at least it's consistent and aesthetically correct. Thank you once again, good sir!

**Comment by Shougo** [comment]
Well, I changed auto preview window size behavior.
