### ISSUE TITLE
possible to configure unite to select grep Pattern: from history/search?

### ISSUE THREAD

**Issue by linuxclef** [Shougo/unite.vim#993]
By default ":Unite grep:.<CR>" allows you to use cursor up/down, or CTRL-f to select a previously searched for pattern when you are prompted with "Pattern: ".

However, I'd like to be able to select a pattern from the "history/search" Unite source [1]. What is the easiest way to achieve this?

Thanks!

---

[1] - well, the ideal for me would be for Unite to combine both the previous grep patterns and history/search.

**Comment by Shougo** [comment]
This feature is really useful?
I don't think so...
Please describe the advantage.

Unfortunatelly, unite.vim does not have the feature.
To implement it, unite.vim can add complete function.

**Comment by linuxclef** [comment]
A common workflow for me is to search for a pattern in the current file (using '*'). If the pattern is not found, I invoke ":Unite grep" to search the source tree for it.

However, if that pattern is a really-long-word, when I am prompted by Unites's "Pattern:" prompt I have 2 options:

1) Copy/paste the really-long-word from the main screen to the "Pattern:" prompt using a mouse.
2) Manually type the really-long-word at the "Pattern:" prompt.

Since I prefer not to use the mouse (and I don't have a mouse on some systems), I am often left with option (1). This is inefficient and error-prone.

It seems to me the best way to avoid (1) is to allow me to select the pattern from a unite buffer, quickly and simply.

**Comment by Shougo** [comment]
OK. I will implement it later.

**Comment by linuxclef** [comment]
Thanks - that will be really useful!

**Comment by Shougo** [comment]
Implemented.

**Comment by linuxclef** [comment]
Thanks! Tab completion on the grep Pattern: now cycles through my previous '*' and 'g*' searches.

**Comment by Shougo** [comment]
It is Vim's feature.

**Comment by linuxclef** [comment]
In which case, this isn't working properly for me. What do I need to do to trigger the display of the search history in a Unite buffer for the grep Pattern: ?

**Comment by Shougo** [comment]
Fixed.

**Comment by linuxclef** [comment]
I still see the normal Pattern: prompt rather than a Unite buffer when I run ":Unite grep". Is this correct?

**Comment by Shougo** [comment]
It is correct.  I don't know you desired situation...
You should describe it.
But I think you should use `:UniteWithCursorWord`.

**Comment by linuxclef** [comment]
Thanks. That seems to show the results of the grep, which is great. However, I would like to be able to see all the previous search patterns in a Unite buffer.

So, If I use '*' on three words (for example, 'foo', 'bar' and 'baz), my search history would be:

foo
bar
baz

So when I call ":Unite grep", rather than typing in 'foo', 'bar' or 'baz' manually, I'd like to see a Unite buffer with 3 lines:

foo
bar
baz

If I then selected 'foo' from that Unite buffer, Unite grep would use 'foo' as the grep pattern and then show me all the grep results, again in a Unite buffer (as happens with :UniteWithCursorWord).

**Comment by Shougo** [comment]
OK.  I get it.
But you can complete the search history words in "Pattern:".
Why don't you use it?
Please describe the reason.

**Comment by Shougo** [comment]
Added grep action.
